apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pubsub-keyvault # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    userAssignedIdentityID: f130a494-bf6a-4906-ab25-ff716944a3ff # Setting this to use workload identity ClientID
    keyvaultName: kv-mfolabs-formations # Set to the name of your key vault
    tenantId: 1e2f522c-2662-4a18-938a-8b61a1ab92d1 # The tenant ID of the key vault