apiVersion: v1
kind: Secret
metadata:
  name: pubsub-secrets
stringData:
  ConnectionStrings__DefaultConnection: "Server=tcp:mssql,1433;Initial Catalog=RabbitMqDemo;Persist Security Info=False;User ID=sa;Password=P@ssw0rd2023!;Connection Timeout=30;"
  RabbitMQ__Password: "admin"
  RabbitMQ__Username: "admin"
  MSSQL_SA_PASSWORD: "P@ssw0rd2023!"