apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: lab-console
          env:
            - name: RabbitMQ__Hostname
              valueFrom:
                configMapKeyRef:
                  key: RabbitMQ__Hostname
                  name: pubsub-cm
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  key: rabbit-password
                  name: rabbit-password
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  key: rabbit-username
                  name: rabbit-username
          image: acrmfolabsform.azurecr.io/matthieuf/pubsub-console:1.0
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "pubsub-keyvault"
